Revert "rust-llvm: Use early variable assignment for the license checksum in rust-llvm.inc"
This reverts commit 5dda6c427a7cca264870f6b7fc64753203e7d30d.

This breaks rust-llvm builds with:
ERROR: QA Issue: rust-llvm-native: LIC_FILES_CHKSUM points to an invalid file: TOPDIR/BUILD/work/x86_64-linux/rust-llvm-native/1.47.0-r0/rustc-1.47.0-src/src/llvm-project/llvm/COPYRIGHT [license-checksum]

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>